homeassistant:
  # Name of the location where Home Assistant is running
  name: Indoor Garden
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  
automation: !include automations.yaml
script: !include scripts.yaml
updater:
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
discovery:
  ignore: apple_tv
system_health:
# View all events in a logbook
logbook:
# Enables configuration UI
config:
# Enables a map showing the location of tracked devices
map:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - mobile_app
      - ios
tts:
  - platform: google_translate
    service_name: google_say
cloud:
mobile_app:
homekit:
ios:

################################## SENSORS #####################################

sensor:
# SYSTEM MONITOR SENSOR
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
# MQTT SENSORS
  - platform: mqtt                       # Status of catch basin under flood table (full or not) 
    name: "Drain Basin"
    state_topic: "feedback/drainBasin"
  - platform: mqtt                       # pH readings
    name: "Atlas pH"
    state_topic: "feedback/atlas_pH"
    icon: mdi:alpha-p-circle 
    unit_of_measurement: 'pH'
    value_template: "{{ (value | float) | round(2) }}"
  - platform: mqtt                        # EC readings
    name: "Atlas EC"
    state_topic: "feedback/atlas_EC"
    icon: mdi:alpha-e-circle 
    value_template: "{{ (value | float) | round(2) }}"
    unit_of_measurement: 'EC'
  - platform: mqtt                         # General messages generated by control box
    name: "Control Box Diagnostics"
    icon: mdi:dip-switch
    state_topic: "feedback/general"
  - platform: mqtt                         # Status of all flood sensors
    name: "Flood Detection"
    state_topic: "feedback/flood"
  - platform: mqtt
    name: "Water Temp"                     # Mixing res water temp
    unit_of_measurement: '°C'
    state_topic: "feedback/waterTemp"
    icon: mdi:coolant-temperature
  - platform: mqtt                         # Air temp in control box (BME280)
    name: "Control Box Temp"
    unit_of_measurement: '°C'
    state_topic: "feedback/boxTemp"
  - platform: mqtt                         # Water level in mixing res (liters)
    name: "Water Level"
    unit_of_measurement: 'Liters'
    state_topic: "feedback/waterLevel"
    icon: mdi:car-coolant-level
  - platform: mqtt                          # Mixing res scale calibration messages
    name: "HX711 Cal"
    state_topic: "feedback/hx711"
  - platform: mqtt                          # Feedback from lightmeasure NodeMCU
    name: "LightMeasure Feedback"
    state_topic: "feedback/lightMeasure"
  - platform: mqtt
    name: "LightMeasure Recording"          # Actual measurements from NodeMCU
    state_topic: "feedback/record"   
# TEMPLATE SENSORS    
  - platform: template
    sensors:
      days_since_grow_start:
        friendly_name: "Days Since Grow Start"
        icon_template: mdi:calendar
        value_template: '{{ ((as_timestamp(now()) - (states.input_datetime.grow_start_date.attributes.timestamp)) | int /60/1440) | round(0) }}'
      current_week_of_grow:
        friendly_name: "Current Week of Grow"
        icon_template: mdi:calendar
        value_template: '{{ ((as_timestamp(now()) - (states.input_datetime.grow_start_date.attributes.timestamp)) | int /60/1440//7 +1)  | round(0) }}'
# TIME/DATE SENSOR
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

################################## SWITCHES ####################################

switch:
# MQTT (8 CHANNEL RELAY BOARD IN CONTROL BOX)
# - For all of the relay board and outlet mqtt switches below, the payload_on and
#   payload_off will be 2 digits. The first is which relay (0 = first relay on the board)
#   and the second will be a 1 if its being turned on and a 0 if being turned off.
# - The ESP32 is programmed to send feedback for the relays and follows the same scheme,
#   so state_on and state_off will be the same as the payload on/off.
  - platform: mqtt
    name: "Relay 8CH_1 0"               #Board #0
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "0:0:1"                 #Format is <BOARD#><RELAY#><STATE>
    payload_off: "0:0:0"
    state_on: "0:0:1"
    state_off: "0:0:0"
  - platform: mqtt
    name: "Relay 8CH_1 1"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "0:1:1"
    payload_off: "0:1:0"
    state_on: "0:1:1"
    state_off: "0:1:0"
  - platform: mqtt
    name: "Relay 8CH_1 2"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "0:2:1"
    payload_off: "0:2:0"
    state_on: "0:2:1"
    state_off: "0:2:0"
  - platform: mqtt
    name: "Relay 8CH_1 3"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "0:3:1"
    payload_off: "0:3:0"
    state_on: "0:3:1"
    state_off: "0:3:0"
  - platform: mqtt
    name: "Relay 8CH_1 4"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "0:4:1"
    payload_off: "0:4:0"
    state_on: "0:4:1"
    state_off: "0:4:0"
  - platform: mqtt
    name: "Relay 8CH_1 5"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "0:5:1"
    payload_off: "0:5:0"
    state_on: "0:5:1"
    state_off: "0:5:0"
  - platform: mqtt
    name: "Relay 8CH_1 6"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "0:6:1"
    payload_off: "0:6:0"
    state_on: "0:6:1"
    state_off: "0:6:0"
  - platform: mqtt
    name: "Relay 8CH_1 7"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "0:7:1"
    payload_off: "0:7:0"
    state_on: "0:7:1"
    state_off: "0:7:0"
# MQTT (4 CHANNEL RELAY BOARD IN POWER BAR)     #Board #1
  - platform: mqtt
    name: "Relay 4CH_1 0"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "1:0:1"                         #Format is <BOARD#><RELAY#><STATE>
    payload_off: "1:0:0"
    state_on: "1:0:1"
    state_off: "1:0:0"
  - platform: mqtt
    name: "Relay 4CH_1 1"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "1:1:1"
    payload_off: "1:1:0"
    state_on: "1:1:1"
    state_off: "1:1:0"
  - platform: mqtt
    name: "Relay 4CH_1 2"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "1:2:1"
    payload_off: "1:2:0"
    state_on: "1:2:1"
    state_off: "1:2:0"
  - platform: mqtt
    name: "Relay 4CH_1 3"
    state_topic: "feedback/relays"
    command_topic: "control/relays"
    payload_on: "1:3:1"
    payload_off: "1:3:0"
    state_on: "1:3:1"
    state_off: "1:3:0"
# MQTT (DOSING PUMPS)       #Pump numbers match indexes in arrays in ESP32 code. 0 = pH Down, 1 = CalMag, 2 = Micro, 3 = Bloom, 4 = Grow, 5 = pH Up
  - platform: mqtt
    name: "pH Down Pump"
    state_topic: "feedback/dosing"
    command_topic: "control/dosing"
    payload_on: "0:60000"   #Format is <pumpNumber><onTime(in milliseconds)>... Sending 60000 means the pump can only run for 1 minute max when turned on manually, to prevent damage.
    payload_off: "0:0"      #Sending "00" as the second parameter will stop the pump regardless of what the initial "on time" was set to.
    state_on: "0:1"         #Format is <pumpNumber><state> (1 = on, 0 = off)
    state_off: "0:0"
  - platform: mqtt
    name: "CalMag Pump"
    state_topic: "feedback/dosing"
    command_topic: "control/dosing"
    payload_on: "1:60000"
    payload_off: "1:0"
    state_on: "1:1"
    state_off: "1:0"
  - platform: mqtt
    name: "Micro Pump"
    state_topic: "feedback/dosing"
    command_topic: "control/dosing"
    payload_on: "2:60000"
    payload_off: "2:0"
    state_on: "2:1"
    state_off: "2:0"
  - platform: mqtt
    name: "Bloom Pump"
    state_topic: "feedback/dosing"
    command_topic: "control/dosing"
    payload_on: "3:60000"
    payload_off: "3:0"
    state_on: "3:1"
    state_off: "3:0"
  - platform: mqtt
    name: "Grow Pump"
    state_topic: "feedback/dosing"
    command_topic: "control/dosing"
    payload_on: "4:60000"
    payload_off: "4:0"
    state_on: "4:1"
    state_off: "4:0"
  - platform: mqtt
    name: "pH Up Pump"
    state_topic: "feedback/dosing"
    command_topic: "control/dosing"
    payload_on: "5:60000"
    payload_off: "5:0"
    state_on: "5:1"
    state_off: "5:0"

############################### DATE/TIME INPUTS ###############################

input_datetime:
  lights_on_time_4x4:
    name: 4x4 Lights On Time
    has_date: false
    has_time: true
  lights_off_time_4x4:
    name: 4x4 Lights Off Time
    has_date: false
    has_time: true
  fert_1_time_4x4:
    name: Fertigation 1 Start Time
    has_date: false
    has_time: true
  fert_2_time_4x4:
    name: Fertigation 2 Start Time
    has_date: false
    has_time: true
  fert_3_time_4x4:
    name: Fertigation 3 Start Time
    has_date: false
    has_time: true
  fert_4_time_4x4:
    name: Fertigation 4 Start Time
    has_date: false
    has_time: true
  fert_5_time_4x4:
    name: Fertigation 5 Start Time
    has_date: false
    has_time: true
  grow_start_date:
    name: Grow Start Date
    has_date: true
    has_time: false

################################ INPUT NUMBERS #################################

input_number:
  target_ph_input:
    name: Target pH
    min: 5.8
    max: 6.5
    step: .1
    icon: mdi:bullseye
    unit_of_measurement: pH
  target_ec_input:
    name: Target EC
    min: 0.5
    max: 2.5
    step: .1
    icon: mdi:bullseye
    unit_of_measurement: EC
  grow_ml_per_liter:
    name: Grow
    min: 0
    max: 10
    step: 1
    icon: mdi:beaker
    unit_of_measurement: mL/L
  micro_ml_per_liter:
    name: Micro
    min: 0
    max: 10
    step: 1
    icon: mdi:beaker
    unit_of_measurement: mL/L
  bloom_ml_per_liter:
    name: Bloom
    min: 0
    max: 10
    step: 1
    icon: mdi:beaker
    unit_of_measurement: mL/L
  calmag_ml_per_liter:
    name: CalMag
    min: 0
    max: 10
    step: 1
    icon: mdi:beaker
    unit_of_measurement: mL/L
  nutrient_batch_size:
    name: Nute Batch Size
    min: 0
    max: 60
    step: 5
    icon: mdi:cup-water
    unit_of_measurement: Liters
# A READ-OUT OF THE LAST 10 pH MEASUREMENTS TO HELP WHEN CALIBRATING
  reading10:
    name: reading10
    mode: box
    min:  1
    max:  14
  reading9:
    name: reading9
    mode: box
    min:  1
    max:  14
  reading8:
    name: reading8
    mode: box
    min:  1
    max:  14
  reading7:
    name: reading7
    mode: box
    min:  1
    max:  14
  reading6:
    name: reading6
    mode: box
    min:  1
    max:  14
  reading5:
    name: reading5
    mode: box
    min:  1
    max:  14
  reading4:
    name: reading4
    mode: box
    min:  1
    max:  14
  reading3:
    name: reading3
    mode: box
    min:  1
    max:  14
  reading2:
    name: reading2
    mode: box
    min:  1
    max:  14
  reading1:
    name: reading1
    mode: box
    min:  1
    max:  14
# FERTIGATION FREQ/DURATION    
  fertigation_duration:
    name: Duration
    min: .5
    max: 10
    step: .5
    icon: mdi:timer
    unit_of_measurement: Minutes
  fertigation_freq:
    name: Frequency
    min: 0
    max: 5
    step: 1
    icon: mdi:pound-box
    unit_of_measurement: Fertigations
# CLIMATE TARGETS    
  humidity_target:
    name: Humidity
    min: 0
    max: 100
    initial: 60    
    step: 5
    icon: mdi:water-percent
    unit_of_measurement: '%'
  temp_target:
    name: Temperature
    min: 15
    max: 30
    initial: 24
    step: 1
    icon: mdi:temperature-celsius
    unit_of_measurement: '°C'
# MANUAL NUTE DISPENSING AND PUMP SPEEDS    
  dispense_nutes:
    name: Dispense Nutes
    mode: box
    min: 0
    max: 150
    icon: mdi:water-pump
    unit_of_measurement: 'mL'
  dosing_pwm_0_ph_down:
    name: pH Down PWM
    mode: box
    min: 190
    max: 254
    icon: mdi:speedometer
    unit_of_measurement: 'PWM'
  dosing_pwm_1_calmag:
    name: CalMag PWM
    mode: box
    min: 190
    max: 254
    icon: mdi:speedometer
    unit_of_measurement: 'PWM'
  dosing_pwm_2_micro:
    name: Micro PWM
    mode: box
    min: 190
    max: 254
    icon: mdi:speedometer
    unit_of_measurement: 'PWM'
  dosing_pwm_3_bloom:
    name: Bloom PWM
    mode: box
    min: 190
    max: 254
    icon: mdi:speedometer
    unit_of_measurement: 'PWM'
  dosing_pwm_4_grow:
    name: Grow PWM
    mode: box
    min: 190
    max: 254
    icon: mdi:speedometer
    unit_of_measurement: 'PWM'
  dosing_pwm_5_ph_up:
    name: pH Up PWM
    mode: box
    min: 190
    max: 254
    icon: mdi:speedometer
    unit_of_measurement: 'PWM' 
# HX711 RES SCALE CALIBRATION FACTOR
  scale_cal_factor:
    name: Scale Calibration Factor
    mode: box
    min: -1000000
    max: 0
    initial: 0
    icon: mdi:scale     

################################ BINARY SENSORS ################################

# FERTIGATION BINARY SENSORS
# These sensors go high/low based on the state of the fertigation frequency
# input number. They are used to control visibility of the fertigation time 
# cards found in the schedule tab of the dashboard. 
binary_sensor:
  - platform: template
    sensors:
      fert_1:
        friendly_name: "One Fert"
        value_template: >-
          {{ states("input_number.fertigation_freq") | float >= 1.0 }}
  - platform: template
    sensors:
      fert_2:
        friendly_name: "Two Ferts"
        value_template: >-
          {{ states("input_number.fertigation_freq") | float >= 2.0 }}
  - platform: template
    sensors:
      fert_3:
        friendly_name: "Three Ferts"
        value_template: >-
          {{ states("input_number.fertigation_freq") | float >= 3.0 }}
  - platform: template
    sensors:
      fert_4:
        friendly_name: "Four Ferts"
        value_template: >-
          {{ states("input_number.fertigation_freq") | float >= 4.0 }}
  - platform: template
    sensors:
      fert_5:
        friendly_name: "Five Ferts"
        value_template: >-
          {{ states("input_number.fertigation_freq") | float >= 5.0 }}
      
################################## RECORDER ####################################

recorder:
  db_url: !secret db_url
  include:
    entities:
      - input_datetime.lights_off_time_4x4
      - input_datetime.lights_on_time_4x4
      - input_number.fertigation_duration
      - input_number.fertigation_freq
      - input_number.calmag_ml_per_liter
      - input_number.grow_ml_per_liter
      - input_number.micro_ml_per_liter
      - input_number.bloom_ml_per_liter
      - input_number.humidity_target
      - input_number.nutrient_batch_size
      - input_number.target_ec_input
      - input_number.target_ph_input
      - input_number.temp_target
      - sensor.atlas_ec
      - sensor.atlas_ph
      - sensor.water_temp
      - switch.ph_down_pump
      - switch.ph_up_pump
